# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Object-Realize-Later
version:      0.15
version_from: lib/Object/Realize/Later.pm
installdirs:  site
requires:
    Scalar::Util:                  0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
